### ISSUE TITLE
Testing APM

### ISSUE THREAD

**Issue by GrandGarcon** [Debond-Protocol/EIP-3475#12]
-  testing the APM (scripts) with scenarios (Fuzzing testing).

**Comment by dr-chain** [comment]
Testing with dapp pools?

**Comment by toufic0710** [comment]
Following tests are passing :
- adding liquidity to one pool when there is no reserve in the pool.
- then removing liquidity for one token.
- then swapping token A for B.

Next tests : See with multiple pools
