### ISSUE TITLE
Cleaning of the EIP-3475 Repo

### ISSUE THREAD

**Issue by dr-chain** [Debond-Protocol/EIP-3475#27]
Following the new implementations, old files, that are not needed, are to be removed.

**Comment by GrandGarcon** [comment]
so if i am correct , following files are not needed 
- [ ] LICENSE.md (old version).
- [ ] specifications.md (this is although mentioned in the core document , butthe description is duplicate ).
- [ ] bonds.png (also do we have to make one to add to represent the current description).

**Comment by dhruvmalik007** [comment]
completed
