### ISSUE TITLE
TASK: Default implementation of IERC3475

### ISSUE THREAD

**Issue by drikssy** [Debond-Protocol/EIP-3475#3]
# Descriptions :

define the functions  that are defined in EIP standard for bonds  as an interface 

## Tasks 
- [X] add the function signature of the bonds 

## Checklists 
- [ ] check with the refactored version of bonds and APM in order to upgrade

**Comment by dr-chain** [comment]
@drikssy @GrandGarcon please tag the reviewer

**Comment by GrandGarcon** [comment]
@toufic0710  and @Edoumou  we can discuss today on this task so as to finalise this for APM

**Comment by dr-chain** [comment]
@drikssy Moving it back since it seems it is not finalized yet. @GrandGarcon

**Comment by GrandGarcon** [comment]
@drikssy  
i had question (may be easy one  ), in the description of the bonds in the paper(page 25 , at the end), there is mention of  the storage of the settlement token :

> The sixth digit and after represents the i-th settlement token ti.

so in that case, if there is functions like total , active and burned supply to be displayed , are these to be managed only by the classId and nonceId as input parameters  , and rather implementing our own functions under  parameter **tokenAddress** or an list that is also maintained in the bond ? or do we consider its only the bank that will be kept tab on that information?  thanks

**Comment by drikssy** [comment]
@GrandGarcon yes you are right, it is implemented in the mapping of description it self
