### ISSUE TITLE
EPIC: New EIP Version Implementation

### ISSUE THREAD

**Issue by dr-chain** [Debond-Protocol/EIP-3475#4]
Implementation of the updated EIP 3475 version

**Comment by GrandGarcon** [comment]
@toufic0710  can you try to integrate the [following](https://github.com/paulrberg/prb-math/blob/main/test/contracts/prbMathSd59x18/PRBMathSD59x18.test.ts) script  for testing the functions, and then we have developed the bonds and other core contracts , we can do some changes for reviewing the operations .
